version: '3'
 
services:
    apache_img:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con
        build:
            context: ./apache
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
        volumes:
            - ../logs/apache:${APACHE_ROOT_DIR}/logs
            - ..:${APACHE_ROOT_DIR}/htdocs/
        ports:
            - ${APACHE_EXPOSED_PORT}:80
        networks:
            public_net:
                ipv4_address: ${APACHE_IP}
        environment:
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
            - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
            - PHP_IP=${PHP_IP}
            - PHP_APP_DIR=${PHP_APP_DIR}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
    mariadb_img:
        container_name: ${COMPOSE_PROJECT_NAME}_mariadb_con
        build:
            context: ./mariadb
            args:
                - MARIADB_CONTAINER_USER=${MARIADB_CONTAINER_USER}
                - MARIADB_CONTAINER_GROUP=${MARIADB_CONTAINER_GROUP}
        volumes:
            - ../logs/mariadb:${MARIADB_LOG_DIR}
            - ../database:${MARIADB_DATA_DIR}
        networks:
            public_net:
                ipv4_address: ${MARIADB_IP}
        environment:
            - MARIADB_CONTAINER_USER=${MARIADB_CONTAINER_USER}
            - MARIADB_CONTAINER_GROUP=${MARIADB_CONTAINER_GROUP}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    php_img:
        container_name: ${COMPOSE_PROJECT_NAME}_php_con
        build:
            context: ./php
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        working_dir: ${PHP_APP_DIR}
        volumes:
            - ..:${PHP_APP_DIR}
            - ../logs/php:${PHP_ROOT_DIR}/logs
        depends_on:
            - apache_img
            - mariadb_img
        networks:
            public_net:
                ipv4_address: ${PHP_IP}
        environment:
            - PHP_ROOT_DIR=${PHP_ROOT_DIR}
            - APACHE_IP=${APACHE_IP}
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
            - MARIADB_IP=${MARIADB_IP}
            - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    mediawiki_setup:
        container_name: ${COMPOSE_PROJECT_NAME}_mw-setup_con
        image: ${COMPOSE_PROJECT_NAME}_php_img
        depends_on: 
            - mariadb_img
            - php_img
            - apache_img
        restart: "no"
        environment:
            - PHP_ROOT_DIR=${PHP_ROOT_DIR}
            - APACHE_IP=${APACHE_IP}
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
            - MARIADB_IP=${MARIADB_IP}
            - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        working_dir: ${PHP_APP_DIR}
        networks:
            public_net:
                ipv4_address: 192.168.0.44
        volumes:
        - ..:${PHP_APP_DIR}
        - ../logs/php:${PHP_ROOT_DIR}/logs
        entrypoint: [ "bash", "-c", "sleep 5 && ./downloadMW.sh"] 
 
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}